# Generated by Django 3.2 on 2023-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_created_time_remove_book_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
